### PR TITLE
Drop code related to Django versions prior to 1.4.4. Closes #491

### LINKED ISSUE #491: Consider testing against Django versions 1.4, 1.4.1, 1.4.2, 1.4.3
In current test suite there are 2 places with conditions related to these versions.
[Here](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/test_layout.py#L283) and [here](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/test_layout.py#L348)
Also in travis config there are only latest versions of 1.4, 1.7, 1.8 and master branches.
My question is - Should we drop these conditions or add old Django version to config?
Personally, I prefer to drop.

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by carltongibson** [comment]
The code doesn't match the description here. (This is "clean up 1.5 version branching")

**Comment by Stranger6667** [comment]
@carltongibson Sorry, can you explain? I didn't get it :(
Did you mean something like:

```python
if django.VERSION[:2] == (1, 4):
```

**Comment by carltongibson** [comment]
Look at the diff. This isn't the 1.4 change.

**Comment by Stranger6667** [comment]
Still confusing... I'll look tomorrow, better :) Thanks

**Comment by carltongibson** [comment]
OK. No problem. 

Here: https://github.com/maraujop/django-crispy-forms/pull/492/files#diff-d4d1e5e71cb5fe5a1542724da1b6604bR275

      if django.VERSION < (1, 5):

**Pull request merged**
