### PR TITLE
Add missing template for bootstrap

### PR DESCRIPTION
**Pull request by gustavi**
This PR will fix a bug using Django 1.9. The template is missing.

### CODE REVIEW

**Comment by gustavi** [comment]
PING

**Comment by carltongibson** [comment]
Already added in #520

**Comment by gustavi** [comment]
Could you make a release then ?

**Comment by carltongibson** [comment]
Coming w/b 4th Jan

**Comment by gustavi** [comment]
Perfect, thank you.

**Comment by gustavi** [comment]
Some news ?

**Comment by gustavi** [comment]
Please could you re-open it ? This is for bootstrap, not boostrap3 ;)

If you could hotfix the v1.6.0 with a v1.6.0 it'll be perfect.

**Comment by carltongibson** [comment]
Ah.  OK. I'll reopen and assess. 

1. For Bootstrap you're better off using Form Actions rather than Button Holder.
2. If you need it before the next release just put the missing template in your own project where it can be picked up.

**Pull request merged**
