### PR TITLE
Fix import error in Django 1.9 (BoundField)

### PR DESCRIPTION
**Pull request by avsd**

### CODE REVIEW

**Comment by carltongibson** [comment]
Ok , good idea — but we need to maintain compatibility with existing Django versions

**Comment by avsd** [comment]
Oh I see! Let me put it in try/catch....

**Comment by avsd** [comment]
It might be a good idea to wait until official Django 1.9 release though: they may change it again.

**Comment by carltongibson** [comment]
Build failed against Python 3.2 because the new version of `coverage` doesn't support it. I've pinned `coverage` in `dev` to fix this. 

If you can rebase this, it should now pass. 

Thanks.

**Comment by avsd** [comment]
Wow, codecov looks amazing! :)

**Comment by carltongibson** [comment]
Comment on #517 suggests this has changed on 1.9.0a2

**Comment by avsd** [comment]
yeah, apparently django-crispy-forms wasn't the only place affected by this change in Django

**Comment by carltongibson** [comment]
OK. We'll hold off on the merge for the moment. 

(If you can point me to the change note that says exactly what's going on I'm happy to review.)

**Comment by zoidbergwill** [comment]
I'm not getting this error against `django-latest` anymore, so maybe we can close this and https://github.com/maraujop/django-crispy-forms/issues/517 ?

**Comment by avsd** [comment]
@zoidbergwill yeah, makes sense

**Comment by Stranger6667** [comment]
In case of merge I propose to move `try/except` blocks to https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/compatibility.py and https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/compatibility.py because these files are intended to contain compatibility-related code.

**Comment by zoidbergwill** [comment]
I don't think we should merge this, because it's fixed [here](https://github.com/django/django/commit/a51070e7434426467869147608c5a8ca58e21e00)/

**Comment by carltongibson** [comment]
@zoidbergwill The comment there seems to imply that this move is coming. (If so we've got it here now so we could add it now) — I can't seem to access the release notes right now but it should say there...

**Comment by zoidbergwill** [comment]
@carltongibson, yeah, you're right. It does all sound that they're moving it for good.

I can't load the docs or the tickets for the Django project at the moment, but I only see some [minor references](https://github.com/django/django/blob/master/docs/releases/1.9.txt#L370-L371) in GitHub.

**Comment by carltongibson** [comment]
Closing [as per advice on Django Developers](https://groups.google.com/d/msg/django-developers/gT5epeBVBWE/8jF7fdl9DgAJ)

> The release notes don't mention it because it's a private API until now. Feel free to do nothing as we're unlikely to remove the backwards compatibility alias for a while, at least until versions < 1.9 are unsupported at which point you could update the import to the new location without needing a conditional.

**Pull request closed without merging**
