### PR TITLE
Measure and report code coverage with Codecov

### PR DESCRIPTION
**Pull request by treyhunner**
Changes:
- Add `make coverage` command which runs code coverage
- Move `runtest.py` to top directory (this puts code coverage files to be in top-directory)
- Allow `./runtests.py --with-coverage` to run tests with code coverage enabled
- Report code coverage to [Codecov][]

Some interesting Codecov [features][]:
- coverage reporting through README badge
- set test pass/fail state on GitHub based on project or patch coverage change thresholds
- see coverage right from GitHub using a browser extension

[Example of django-crispy-forms coverage on Codecov][example]

If measuring coverage through Codecov is deemed desirable but moving `runtests.py` to the top directory in undesirable, I can look into alternate solutions.

**Full disclosure**: I work for Codecov

[codecov]: https://codecov.io/
[example]: https://codecov.io/github/treyhunner/django-crispy-forms/crispy_forms/layout.py?ref=7f5e264d7069406045d5db5259372a17d0b5e037#l-412
[features]: https://codecov.io/#features

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @treyhunner — thanks for this. I saw @tomchristie talking highly of Codecov, so I'lll give this a look. (Just need to do a new release first!)

**Comment by tomchristie** [comment]
codecov gets a thumbs up from me, yup

**Comment by treyhunner** [comment]
@carltongibson I'm happy to answer any questions and rebase to avoid conflicts as needed

@tomchristie thanks for the kind words :smile_cat:

**Comment by carltongibson** [comment]
@treyhunner We've made a few changes to the testing set up here. (Just have #467 to go) Ready to look at this now. If you could update that would be AWESOME! :-)

**Comment by treyhunner** [comment]
@carltongibson I rebased the pull request and used `pytest-cov`.

I added a `.coveragerc` file that enables branch coverage.  This allows for missing else branches to be caught, [like this one][branch].

[Here's an example coverage report][report]

I moved `runtests.py` to the top directory to make the coverage report generate there.  I may be able to get it working without moving that file if you don't like that change.  Let me know! :smiley_cat: 

[branch]: https://codecov.io/github/maraujop/django-crispy-forms/crispy_forms/bootstrap.py?ref=169ef354c78d6699c8d57211b49781bee3158507#l-324
[report]: https://codecov.io/github/maraujop/django-crispy-forms?ref=169ef354c78d6699c8d57211b49781bee3158507

**Comment by carltongibson** [comment]
Thanks @treyhunner we'll give this a run. 👍

**Pull request merged**
