### PR TITLE
Reduce code duplication

### PR DESCRIPTION
**Pull request by Stranger6667**
This is small improvement. Basically I've moved string concatenation to separate method and replace it with ```str.join```

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @Stranger6667 — this is great. 

Can you apply the same fix to [`crispy_forms.bootstrap.FormActions`](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/bootstrap.py#L61)? 

Other than that I think we're good to merge. Great one!

**Comment by carltongibson** [comment]
In face there are a few opportunities for the same fix in that file...

**Comment by Stranger6667** [comment]
Hi, @carltongibson ! I'll do that :)

**Comment by carltongibson** [comment]
Good man! :+1:

**Comment by Stranger6667** [comment]
Done, but [here](https://github.com/maraujop/django-crispy-forms/commit/3097114bf3bb30a0968596cd31f2fa20e153abca#diff-5ad819bee6ab03888884dd8009cb93a2R286) now it iterates over all fields twice :( Not a big thing in my opinion, but code is cleaner now

**Comment by carltongibson** [comment]
> ...it iterates over all fields twice...

I can't see an issue there. We're not mining bitcoin. ;-)

**Comment by carltongibson** [comment]
Fancy adding yourself to `Contributors.txt`?

**Comment by carltongibson** [comment]
Thanks for the input @Stranger6667!

**Pull request merged**
