### PR TITLE
Convert test_layout.py module

### PR DESCRIPTION
**Pull request by Stranger6667**
About the same like #470, but I leaved some classes, just to not mark all tests separately. Probably further there will be some restructuring.

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. A couple of things: 

1. Can you squash the commits here? 
2. Whilst it's more contemporary after the changes, it seems like I lot of work for no great gains in terms of amount of code or clarity. 

On 2, I'm happy to merge it but I'm wondering about the value of the gain. What's your view there?

**Comment by carltongibson** [comment]
For example, whilst I'd write new code with asserts, I'm not sure of the benefit of rewriting to eliminate all the assertEquals calls. (One of the advantages of pytest is, surely, that it just works with your existing tests...)

**Comment by Stranger6667** [comment]
Yes, I'll squash it.
It is intermediate step to get all features of py.test. Now it is just semi-automatic change.
Unfortunately default ```TestCase``` from unittest [can't obtain](https://pytest.org/latest/unittest.html) all features of py.test like parametrization or fixture mechanism.
It is a main reason to remove all ```unittests.TestCase``` usage. So next it will be possible to use fixtures like that:

```python
@pytest.fixture(autouse=True, params=('uni_form', 'bootstrap', 'bootstrap3'))
def template_packs(request, settings):
    settings.CRISPY_TEMPLATE_PACK = request.param
```

And all tests can be executed in single run. Also there are a lot of forms/helpers/layouts, which can be parametrized. In future, for example, params can be obtained from settings and if you want to add new template pack, then it will be automagically tested against current test suite.

Minor benefit, but all tests on my latest branch with completed py.test integration runs for ~ 6 sec vs 3min 19 sec on master branch (Django 1.8.3). Because of fixture caching and more simple test suite at all.

These changes will lead to simper test suite, which can be easily extended. May be it will be better to create separate branch with some rewritten tests examples?

P.S. Also I've found some errors in tests. But I'm not sure should it be fixed in current tests or in py.test version.

Thanks! :)

**Comment by carltongibson** [comment]
OK, cool. I don't want to put you off — great work all of it.

I don't mind where you  fix things — whatever is easiest — but please keep logic changes separate from straight porting, otherwise it'll make reviewing difficult/slow.

**Pull request merged**
