### PR TITLE
Django 1.10 compat

### PR DESCRIPTION
**Pull request by davidszotten**

### CODE REVIEW

**Comment by carltongibson** [comment]
@davidszotten This is great thanks. 

Looks like time for a new release.

**Comment by jhancia** [comment]
Hi, really appreciate this library.  Any chance we could have a pypi release? Trying to get a project up and running with django 1.10.  Thank you!!

**Comment by carltongibson** [comment]
@jhancia Yep new release is on the way. 

In the meantime you can use pip to install straight from GitHub, using the [VCS Support features](https://pip.pypa.io/en/latest/reference/pip_install/#vcs-support).

You'd need something like this in your requirements file:

```
-e git+https://github.com/django-crispy-forms/django-crispy-forms@dev#egg=django-crispy-forms
```

**Comment by jhancia** [comment]
Thanks, that helps.  BTW, is this holding up the next release? [https://github.com/django-crispy-forms/django-crispy-forms/pull/582](url)

**Comment by carltongibson** [comment]
https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/1.6.1

**Pull request merged**
