### PR TITLE
Added semantic-ui theme

### PR DESCRIPTION
**Pull request by acidjunk**
Created a basic Semantic-UI theme for crispy-forms
http://semantic-ui.com/

### CODE REVIEW

**Comment by acidjunk** [comment]
I brought the PR in sync again. Hope it will be merged soon.

**Comment by carltongibson** [comment]
Hey @acidjunk — Thanks for updating the PR. 

I'm not sure about merging it in... — Basically I need to keep the maintenance burden of the project as low as possible — and the trouble with adding extra template packs is that they'll inevitably leads to extra work as gaps/errors/additions are found/arrive.

What I'd prefer is if you would maintain it as a third party template pack. I'd be very happy to link to it in the docs etc...

**Comment by acidjunk** [comment]
I would happily maintain stuff regarding the template. Still looking for an easy way to test if I "got" all form elements/sets.

Anyway: https://github.com/acidjunk/crispy-forms-semanticUI-templates

**Comment by carltongibson** [comment]
> Still looking for an easy way to test if I "got" all form elements/sets.

Hmmm. Yes. I'm not sure such a way exists... 

> Anyway: https://github.com/acidjunk/crispy-forms-semanticUI-templates

OK. Awesome. 

I'm going to close this. If you adjust the docs here: http://django-crispy-forms.readthedocs.org/en/latest/install.html#template-packs — perhaps creating a "Third-Party" subsection — that would be perfect. 

(If not open an issue referencing this one and I can add the link when I have a moment myself.)

**Comment by zoidbergwill** [comment]
> Still looking for an easy way to test if I "got" all form elements/sets.

I have a [crispy-test-project](https://github.com/zoidbergwill/crispy-test-project) that I've used for testing template packs, but it isn't anything official, though I'd love to maybe add more to it so it could validate template packs or something for missing CSS classes and stuff, though this would be a separate ticket if we wanted to consider development stuff for testing stuff like that.

**Comment by acidjunk** [comment]
Thanks; that looks very useful indeed.
Will dive into it next week.

**Pull request closed without merging**
