### PR TITLE
Fixes based on coverage report

### PR DESCRIPTION
**Pull request by Stranger6667**
Unfortunately some tests became broken, and I don't know yet how to fix it. Please, take a look at failures, I believe, that it can be fixed easily.

Thanks!

### CODE REVIEW

**Comment by Stranger6667** [comment]
Probably ```test_crispy_addon``` should be marked only for bootstrap template pack

**Comment by carltongibson** [comment]
[Bootstrap only layout objects](http://django-crispy-forms.readthedocs.org/en/latest/layouts.html#bootstrap-layout-objects)

**Comment by carltongibson** [comment]
Needs to run for `bootstrap` and `bootstrap3`.

**Comment by Stranger6667** [comment]
I've removed ```field_class``` and ```label_class``` from ```bootstrap3/layout/prepended_appended_text.html``` template, because there are no such variables in context inside PrependedAppendedText (also, whole extra_context here is overridden) or inside crispy_addon tag.
This change affects only cases with manual rendering of template without any django-crispy-forms features. As I see. May be I'm wrong here. Please, advice, what is the proper decision here?

**Comment by carltongibson** [comment]
@Stranger6667 Please drop the change to `../layout/prepended_appended_text.html`. This attributes come down from the `Helper` and they're in all the templates. Worst case is they evaluate to an empty string. 

If you're convinced they're redundant then open a separate issue and show that in the description, so I can see it too. 

Thanks.

**Comment by Stranger6667** [comment]
@carltongibson Done! Test fails because of ```InvalidVarException``` setting, which raises exception.

**Comment by Stranger6667** [comment]
If you want, I can squash commits

**Comment by carltongibson** [comment]
Hang on. I'm trying to follow what you're changing here. — "Got an exception so removed it". Can you talk me through the last changes so I can make sure. Thanks!

**Comment by Stranger6667** [comment]
[Here](https://github.com/maraujop/django-crispy-forms/pull/484/files#diff-d2f0e621ceb7e1b3ba6428723417f202L35) we have special class which rises exception if there is no such variable. It differs from default Django behavior. As you pointed it will be rendered as empty string.
So, test failure was related to test suite settings, not to any bug in the codebase.

**Comment by carltongibson** [comment]
Yes. I was just looking to see if it was used anywhere. But the tests pass, so it can't really be can it. :-)

**Pull request merged**
