### PR TITLE
Fix various typos, small amount of PEP8

### PR DESCRIPTION
**Pull request by Stranger6667**
Fixes #317, fixes #340, fixes #343, fixes #374, fixes #399, fixes #400, fixes #421, fixes #422, fixes #433

### CODE REVIEW

**Comment by Stranger6667** [comment]
This PR covers:
* #317
* #340
* #343
* #374
* #399
* #400
* #421
* #422
* #433

**Comment by carltongibson** [comment]
@Stranger6667. Ok this is good.

Can I ask you to use the [Fixes #... syntax](https://help.github.com/articles/closing-issues-via-commit-messages/) so we automatically close the issues/PRs when merging?

**Comment by carltongibson** [comment]
I guess Flake8 is next on the list...

**Comment by Stranger6667** [comment]
@carltongibson , thanks, didn't know about such feature. But I wonder if it works with PR description

**Comment by carltongibson** [comment]
If you can update this I'll merge it.

**Comment by carltongibson** [comment]
> ... I wonder if it works with PR description

Yes. It does. :-)

Thanks for all the work here. Really great!

**Pull request merged**
