### PR TITLE
Minor Bootstrap 4 improvements

### PR DESCRIPTION
**Pull request by zoidbergwill**
Fix labels for checkboxes and radiobuttons, and fix `form-control-lg` and `form-control-sm` for PrependedAppendedText widgets.

Closes https://github.com/maraujop/django-crispy-forms/issues/531

Before:

image

After:

image

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Tests are only failing on Django 1.4, will look into it.

**Comment by carltongibson** [comment]
Lets drop 1.4 support. It's EOL

**Comment by zoidbergwill** [comment]
Can I strip it out in this PR?

**Comment by zoidbergwill** [comment]
I dropped Python 2.6 and Django 1.4 support, and made it successfully test Django 1.9 and Python 3.5.

Let me know if I should put that in a separate PR.

**Comment by carltongibson** [comment]
Great job. Thanks!

**Pull request merged**
